#!/bin/bash

FILE=functions/.env

# variables
ENV=${1:-$ENV}
RELEASE=${2:-$RELEASE}
ADMIN_URL=${3:-$ADMIN_URL}
BACKOFFICE_URL=${4:-$BACKOFFICE_URL}
PROJECT_ID=${5:-$PROJECT_ID}
AUTH_DOMAIN=${6:-$AUTH_DOMAIN}
API_KEY=${7:-$API_KEY}

touch $FILE
echo ENV=$ENV >> $FILE
echo RELEASE=$RELEASE >> $FILE
echo ADMIN_URL=$ADMIN_URL >> $FILE
echo BACKOFFICE_URL=$BACKOFFICE_URL >> $FILE
echo PROJECT_ID=$PROJECT_ID >> $FILE
echo AUTH_DOMAIN=$AUTH_DOMAIN >> $FILE
echo API_KEY=$API_KEY >> $FILE
