name: Firebase Publish - HMG

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      ENV: HMG
      FIREBASE_PROJECT: clube-do-afiliado-homolog
      FIREBASE_PROJECT_ENV: homolog
    secrets: inherit