name: Firebase Publish - HMG

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      FIREBASE_PROJECT: clube-do-afiliado-homolog
      ENV: prod
    secrets: inherit