name: Firebase Publish - PROD

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      ENV: PROD
      FIREBASE_PROJECT: clube-do-afiliado-stg
      FIREBASE_PROJECT_ENV: stg
    secrets: inherit