name: Deploy

on:
  workflow_call:
    inputs:
      FIREBASE_PROJECT:
        required: true
        type: string
      ENV:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    env:
      # Environment
      ENV: ${{ inputs.ENV }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install Firebase CLI globally
        run: npm install -g firebase-tools
      
      - name: Check Firebase CLI
        run: firebase --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Configure cleanup policy
        run: npx firebase-tools functions:artifacts:setpolicy --force --token ${{ secrets.FIREBASE_TOKEN }}

      # Passa as variáveis do GitHub Secrets para o Firebase
      - run: |
          firebase functions:config:set \
            ENV="prod"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Publish on Firebase
        uses: jsryudev/deploy-firebase-functions@v20.0.1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ inputs.FIREBASE_PROJECT }}
          FUNCTIONS_DIR: functions
          args: deploy --force
